check
Signed-off-by: Shurtu-gal <ashishpadhy1729@gmail.com>

diff --git a/.github/workflows/release-with-changesets.yml b/.github/workflows/release-with-changesets.yml
--- a/.github/workflows/release-with-changesets.yml
+++ b/.github/workflows/release-with-changesets.yml
@@ -14,69 +14,68 @@ on:
       - next
 
 jobs:
-  # test-nodejs:
-  #   # We just check the message of the first commit as there is always just one commit because we squash into one before merging
-  #   # "commits" contains an array of objects where one of the properties is the commit "message"
-  #   # Release workflow will be skipped if release conventional commits are not used
-  #   if: |
-  #     (startsWith( github.event.commits[0].message , 'fix:' ) ||
-  #     startsWith( github.event.commits[0].message, 'fix!:' ) ||
-  #     startsWith( github.event.commits[0].message, 'feat:' ) ||
-  #     startsWith( github.event.commits[0].message, 'chore(release):' ) ||
-  #     startsWith( github.event.commits[0].message, 'feat!:' ))
-  #   name: Test NodeJS release on ${{ matrix.os }}
-  #   runs-on: ${{ matrix.os }}
-  #   strategy:
-  #     matrix:
-  #       os: [ubuntu-latest, macos-latest, windows-latest]
-  #   steps:
-  #     - name: Set git to use LF # To once and for all finish the never-ending fight between Unix and Windows
-  #       run: |
-  #         git config --global core.autocrlf false
-  #         git config --global core.eol lf
-  #       shell: bash
-  #     - name: Checkout repository
-  #       uses: actions/checkout@v4
-  #     - name: Check if Node.js project and has package.json
-  #       id: packagejson
-  #       run: test -e ./package.json && echo "exists=true" >> $GITHUB_OUTPUT || echo "exists=false" >> $GITHUB_OUTPUT
-  #       shell: bash
-  #     - if: steps.packagejson.outputs.exists == 'true'
-  #       name: Check package-lock version
-  #       uses: asyncapi/.github/.github/actions/get-node-version-from-package-lock@master
-  #       id: lockversion
-  #     - if: steps.packagejson.outputs.exists == 'true'
-  #       name: Setup Node.js
-  #       uses: actions/setup-node@v4
-  #       with:
-  #         node-version: "${{ steps.lockversion.outputs.version }}"
-  #         registry-url: "https://registry.npmjs.org"
-  #     - if: steps.lockversion.outputs.version == '18' && matrix.os == 'windows-latest'
-  #       name: Install npm cli 8
-  #       shell: bash
-  #       # npm cli 10 is buggy because of some cache issues
-  #       run: npm install -g npm@8.19.4
-  #     - if: steps.packagejson.outputs.exists == 'true'
-  #       name: Install dependencies
-  #       shell: bash
-  #       run: npm ci
-  #     - if: steps.packagejson.outputs.exists == 'true'
-  #       name: Run test
-  #       run: npm test --if-present
-  #     - if: failure() # Only, on failure, send a message on the 94_bot-failing-ci slack channel
-  #       name: Report workflow run status to Slack
-  #       uses: 8398a7/action-slack@fbd6aa58ba854a740e11a35d0df80cb5d12101d8 # v3.15.1
-  #       with:
-  #         status: ${{ job.status }}
-  #         fields: repo,action,workflow
-  #         text: "Release workflow failed in testing job"
-  #       env:
-  #         SLACK_WEBHOOK_URL: ${{ secrets.SLACK_CI_FAIL_NOTIFY }}
+  test-nodejs:
+    # We just check the message of the first commit as there is always just one commit because we squash into one before merging
+    # "commits" contains an array of objects where one of the properties is the commit "message"
+    # Release workflow will be skipped if release conventional commits are not used
+    if: |
+      (startsWith( github.event.commits[0].message , 'fix:' ) ||
+      startsWith( github.event.commits[0].message, 'fix!:' ) ||
+      startsWith( github.event.commits[0].message, 'feat:' ) ||
+      startsWith( github.event.commits[0].message, 'chore(release):' ) ||
+      startsWith( github.event.commits[0].message, 'feat!:' ))
+    name: Test NodeJS release on ${{ matrix.os }}
+    runs-on: ${{ matrix.os }}
+    strategy:
+      matrix:
+        os: [ubuntu-latest, macos-latest, windows-latest]
+    steps:
+      - name: Set git to use LF # To once and for all finish the never-ending fight between Unix and Windows
+        run: |
+          git config --global core.autocrlf false
+          git config --global core.eol lf
+        shell: bash
+      - name: Checkout repository
+        uses: actions/checkout@v4
+      - name: Check if Node.js project and has package.json
+        id: packagejson
+        run: test -e ./package.json && echo "exists=true" >> $GITHUB_OUTPUT || echo "exists=false" >> $GITHUB_OUTPUT
+        shell: bash
+      - if: steps.packagejson.outputs.exists == 'true'
+        name: Check package-lock version
+        uses: asyncapi/.github/.github/actions/get-node-version-from-package-lock@master
+        id: lockversion
+      - if: steps.packagejson.outputs.exists == 'true'
+        name: Setup Node.js
+        uses: actions/setup-node@v4
+        with:
+          node-version: "${{ steps.lockversion.outputs.version }}"
+          registry-url: "https://registry.npmjs.org"
+      - if: steps.lockversion.outputs.version == '18' && matrix.os == 'windows-latest'
+        name: Install npm cli 8
+        shell: bash
+        # npm cli 10 is buggy because of some cache issues
+        run: npm install -g npm@8.19.4
+      - if: steps.packagejson.outputs.exists == 'true'
+        name: Install dependencies
+        shell: bash
+        run: npm ci
+      - if: steps.packagejson.outputs.exists == 'true'
+        name: Run test
+        run: npm test --if-present
+      - if: failure() # Only, on failure, send a message on the 94_bot-failing-ci slack channel
+        name: Report workflow run status to Slack
+        uses: 8398a7/action-slack@fbd6aa58ba854a740e11a35d0df80cb5d12101d8 # v3.15.1
+        with:
+          status: ${{ job.status }}
+          fields: repo,action,workflow
+          text: "Release workflow failed in testing job"
+        env:
+          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_CI_FAIL_NOTIFY }}
 
   release:
-    # needs: [test-nodejs]
+    needs: [test-nodejs]
     name: Publish to any of NPM, GitHub, or Docker Hub
-    if: startsWith(github.event.commits[0].message , 'release:') || startsWith( github.event.commits[0].message , 'chore(release):' )
     runs-on: ubuntu-latest
     permissions:
       contents: write
@@ -129,10 +128,10 @@ jobs:
           setupGitUser: false
         env:
           GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
-          GIT_AUTHOR_NAME: ash17290
-          GIT_AUTHOR_EMAIL: shurtugal3023@gmail.com
-          GIT_COMMITTER_NAME: ash17290
-          GIT_COMMITTER_EMAIL: shurtugal3023@gmail.com
+          GIT_AUTHOR_NAME: asyncapi-bot
+          GIT_AUTHOR_EMAIL: info@asyncapi.io
+          GIT_COMMITTER_NAME: asyncapi-bot
+          GIT_COMMITTER_EMAIL: info@asyncapi.io
 
       - name: Publish to NPM directly (skip if version already published)
         if: steps.packagejson.outputs.exists == 'true' && steps.release.outputs.hasChangesets == 'false'
@@ -147,3 +146,13 @@ jobs:
             echo "Publishing version $VERSION of package $PACKAGE_NAME to NPM."
             npm publish --provenance
           fi
+
+      - if: failure() # Only, on failure, send a message on the 94_bot-failing-ci Slack channel
+        name: Report workflow run status to Slack
+        uses: 8398a7/action-slack@fbd6aa58ba854a740e11a35d0df80cb5d12101d8 # v3.15.1
+        with:
+          status: ${{ job.status }}
+          fields: repo,action,workflow
+          text: "Release workflow failed in release job"
+        env:
+          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_CI_FAIL_NOTIFY }}
